### PR TITLE
Add linters

### PR DESCRIPTION
**Pull request by noelfoka**
In this branch, I did:

- [ ] Create index.html file and edit it.
- [ ] Create style.css file and edit it.
- [ ] create linter branch.
- [ ] configure linters.

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @noelfoka 👋👋👋, 

tryagain


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are correctly setup and they are passing👍.
- [x] Github flow have been used👍.
- [x] A `index.html` and `styles.css` file have been created👍.
- [x] A `.gitignore` file have been created and the `test.nd` and `node_modules` file have been added to it👍.


## Required Changes ♻️

- [ ] Just as required in this milestone, you are to create a descriptive readme using the microverse [readme template](https://github.com/microverseinc/readme-template)😉. Kindly make use of this template, follow the instructions given in the [template](https://github.com/microverseinc/readme-template) and create a descriptive readme as this gives your project a more professional look👍.
image



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by noelfoka** [comment]
I added README.md file and edit it

**Comment by Ibizugbe** [comment]
> I added README.md file and edit it

Nice job @noelfoka 😉 Kindly resubmit on your dashboard for another review👍.

**Review by Olamarx — APPROVED** [review]
Hi @noelfoka, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Readme file professional ✔️
- Linters passed ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
